Solution
mate-academy/js_inverse_robot pull request #1462
Opened 2022-09-18 13:38 UTC by DimaFlacko

2022-09-18 13:47 UTC, MAKSOti approved these changes
GJ

2022-09-19 17:24 UTC, silchyn requested changes

2022-09-19 17:24 UTC, silchyn commented on src/inverseRobot.js
> +    }
```suggestion
    if (inversedRobot.hasOwnProperty([robot[key]])) {
      return null;
    }
    
    inversedRobot[robot[key]] = key;
```

2022-09-20 13:46 UTC, silchyn approved these changes
Cool!

2023-02-20 16:34 UTC, closed without merging