Solution
mate-academy/js_inverse_robot pull request #1512
Opened 2022-10-18 07:16 UTC by Andriy-Shymkiv

2022-10-20 10:51 UTC, taraselnik approved these changes
perfect, but how? )) give me a link please to read about

2022-10-20 11:27 UTC, Andriy-Shymkiv commented
> perfect, but how? )) give me a link please to read about

krutyv vertyv i poluchylos'

2022-10-20 14:35 UTC, mykola-koval requested changes

2022-10-20 14:35 UTC, mykola-koval commented on src/index.html
> +</html>
why do we need this?

2022-10-20 14:35 UTC, mykola-koval commented on src/inverseRobot.js
> +    if (inverse[robot[key]]) {
checklist 2

2022-10-21 07:48 UTC, mykola-koval approved these changes

2024-03-27 08:27 UTC, closed without merging