Finished task
mate-academy/js_inverse_robot pull request #1646
Opened 2022-11-23 16:57 UTC by JzSol

2022-11-23 19:23 UTC, lefteris-L approved these changes
Short and simple 💯

2022-11-24 12:56 UTC, mgrinko requested changes

2022-11-24 12:56 UTC, mgrinko commented on src/inverseRobot.js
> +    revese[robot[keys]] = keys;
A blank line between a block and the next command

```suggestion
    }
    
    revese[robot[keys]] = keys;
```

2022-11-24 12:56 UTC, mgrinko commented on src/inverseRobot.js
> +  for (const keys in robot) {
Why do you call a variable containing a current `key` in plural form?

2022-11-24 12:56 UTC, mgrinko commented on src/inverseRobot.js
> +  const revese = {};
`reverse` is a verb
It is a good name for a function but not for a variable storing an object

2022-11-24 12:56 UTC, mgrinko commented on src/inverseRobot.js
>    // write code here
Do you really need this comment?

2022-11-28 06:48 UTC, naziamoff approved these changes
Good job!
Just small comment about naming

2022-11-28 06:48 UTC, naziamoff commented on src/inverseRobot.js
> +  const result = {};
your variables should have more descriptive names, so you should avoid naming them like `result` or `object`.
What about `inversedRobot`?

2026-05-16 06:31 UTC, closed without merging