Solution
mate-academy/js_inverse_robot pull request #1672
Opened 2022-11-24 22:24 UTC by batstolya

2022-11-25 12:34 UTC, RedkoSerhii approved these changes

2022-11-25 13:42 UTC, solaryasha requested changes

2022-11-25 13:42 UTC, solaryasha commented on src/inverseRobot.js
> +  const obj = {};
Сheck the p3 of the checklist

2022-11-25 13:42 UTC, solaryasha commented on src/inverseRobot.js
> +    if (!obj[robot[key]]) {
Check the p2 of the checklist

2022-11-25 13:42 UTC, solaryasha commented on src/inverseRobot.js
> +    } else {
Check the p4 of the checklist

2022-11-28 07:11 UTC, valerii-derkach requested changes

2022-11-28 07:11 UTC, valerii-derkach commented on src/inverseRobot.js
> +    updatedRobot[robot[key]] = key;
```suggestion
    updatedRobot[robot[key]] = key;
```

[robot[key]] -- checklist p1

2022-11-28 11:44 UTC, batstolya commented on src/inverseRobot.js
> +    updatedRobot[robot[key]] = key;
@valerii-derkach what do you mean?
```suggestion
	const value = robot[key];
    updatedRobot[value] = key;
    
    is it right?
```

2022-11-28 12:38 UTC, valerii-derkach approved these changes

2022-11-28 12:38 UTC, valerii-derkach commented on src/inverseRobot.js
> +    const newValue = key;
```suggestion
  for (const key in robot) {
    const newKey = robot[key];
```
you can use `key`

2026-07-13 23:08 UTC, closed without merging