Solution
mate-academy/js_inverse_robot pull request #1816
Opened 2023-01-08 08:34 UTC by Zelinskyi-Serhii

2023-02-12 18:51 UTC, Bogdan-Mykhailov approved these changes
Good job!

2023-02-14 14:27 UTC, Andr1yK requested changes

2023-02-14 14:27 UTC, Andr1yK commented on src/inverseRobot.js
>    // write code here
```suggestion
```

2023-02-14 14:27 UTC, Andr1yK commented on src/inverseRobot.js
> +  }
let's use `for of` loop, and avoid increasing complexity

2023-02-15 09:03 UTC, Andr1yK approved these changes

2023-07-12 20:13 UTC, closed without merging