inverseRobot solution
mate-academy/js_inverse_robot pull request #1929
Opened 2023-02-13 15:30 UTC by MaksymMaliuk

2023-02-13 16:28 UTC, Lilu580 reviewed
Gj

2023-02-14 10:57 UTC, Stepan-TS approved these changes

2023-02-14 14:04 UTC, Andr1yK requested changes
now your code had a big algorithmic complexity, let's simplify it)

U can use just `for in` loop

2023-02-14 14:04 UTC, Andr1yK commented on src/inverseRobot.js
> +  const value = Object.values(robot);
array with keys named as a key.. something is wrong

2023-02-14 17:55 UTC, Andr1yK approved these changes

2023-02-14 17:55 UTC, Andr1yK commented on src/inverseRobot.js
> +    newRobot[robot[key]] = key;
```suggestion
    if (newRobot[robot[key]]) {
      return null;
    }

    newRobot[robot[key]] = key;
```

2024-04-21 23:06 UTC, closed without merging