Solution
mate-academy/js_inverse_robot pull request #212
Opened 2020-12-15 15:34 UTC by dmitriy-tverdokhlibov

2020-12-15 19:34 UTC, vpolets requested changes

2020-12-15 19:34 UTC, vpolets commented on src/inverseRobot.js
> +  }
молодець, але можна зробити це ж саме набагато меншими зусиллями

створи пустий об'єкт, додавай в нього нові ключі, але перед цим перевіряй чи такого ключа ще немає, якщо ключ є - повертаємо одразу null і все

в допомогу метод hasOwnProperty

2020-12-16 18:03 UTC, dmitriy-tverdokhlibov commented on src/inverseRobot.js
> +  }
Хотел использовать этот метод. Только я не додумался проверять в новом обьекте) Спасибо

2020-12-17 14:42 UTC, vpolets approved these changes

2025-04-23 18:59 UTC, closed without merging