inverseRobot solution
mate-academy/js_inverse_robot pull request #2206
Opened 2023-05-01 17:48 UTC by DidenkoDenis306

2023-05-08 07:57 UTC, 33Orange requested changes
Use `for .. in` loop to iterate through the props of the "robot" object instead of using 2 separated arrays of keys and values.

2023-05-08 07:57 UTC, 33Orange commented on src/inverseRobot.js
> +  for (let i = 0; i < robotKeys.length; i++) {
Instead of using separate arrays for keys and values, use a 'for...in' loop to iterate through the properties of the 'robot' object.

2023-05-08 07:57 UTC, 33Orange commented on src/inverseRobot.js
> +  const robotValues = Object.values(robot).reverse();
You don't need to use reverse. Both times you flip arrays for no reason

2023-05-08 07:57 UTC, 33Orange commented on src/inverseRobot.js
> +    invRobot[robotValues[i]] = robotKeys[i];
You can take the value inside the iteration and not create 2 extra arrays.

2023-05-09 19:25 UTC, Anna-Tkachenko requested changes

2023-05-09 19:25 UTC, Anna-Tkachenko commented on src/inverseRobot.js
> +  const invRobot = {};
Don't make the variable name shortened. Let's use full variable names

2023-05-09 19:31 UTC, Anna-Tkachenko approved these changes
⭐️

2024-07-09 10:18 UTC, closed without merging