Solution
mate-academy/js_inverse_robot pull request #2257
Opened 2023-05-09 15:40 UTC by bohdan-mykhailenko

2023-05-09 21:25 UTC, SofiaLiubchenko approved these changes
good job

2023-05-10 11:46 UTC, 33Orange requested changes
Good job!

Just one moment. Let's change the condition in the `if` statement using the object's hasOwnProperty method

2023-05-10 11:46 UTC, 33Orange commented on src/inverseRobot.js
> +    if (newRobot[value]) {
Change the condition to check if the property exists in the object, use 'hasOwnProperty' method.

2023-05-11 14:54 UTC, silchyn approved these changes

2024-08-02 21:59 UTC, closed without merging