Solution
mate-academy/js_inverse_robot pull request #2266
Opened 2023-05-09 21:21 UTC by PanyaPrimal

2023-05-10 09:50 UTC, ghost approved these changes

2023-05-10 13:59 UTC, cephy77 approved these changes
Good one 👍 )

2023-05-10 15:49 UTC, dinaminahi requested changes

2023-05-10 15:49 UTC, dinaminahi commented on src/inverseRobot.js
> +    const value = robot[key];
Try to come up with more descriptive variable name here, and everything else is great!

2023-05-11 14:58 UTC, silchyn approved these changes

2025-12-18 12:06 UTC, closed without merging