add task solution
mate-academy/js_inverse_robot pull request #2548
Opened 2023-07-30 15:32 UTC by Koliras

2023-07-30 23:16 UTC, AntonHerasymov approved these changes
Good job!

2023-07-31 20:05 UTC, dffUqp requested changes
Almost done:smiley:

2023-07-31 20:05 UTC, dffUqp commented on src/inverseRobot.js
> +  const VALUES = Object.keys(robot);
I think we can make this shorter, let's get robot value in `for` loop and then use something like this:
![image](https://github.com/mate-academy/js_inverse_robot/assets/96138503/d87ee0d1-a787-4200-a673-258e3736af34)

2023-07-31 20:05 UTC, dffUqp commented on src/inverseRobot.js
> +  const INVERSED_ROBOT = {};
it's better to rename this variable to lowercase, basically we use upper + snake keys for static variables that won't be changed

learn more about javascript naming convention - [link](https://www.robinwieruch.de/javascript-naming-conventions/)

2023-08-01 16:52 UTC, BudnikOleksii approved these changes
Nicely done👍

2024-12-16 15:13 UTC, closed without merging