Solution
mate-academy/js_inverse_robot pull request #293
Opened 2021-03-09 19:54 UTC by vasylevskaya

Я забыла создать ветку develop. Надеюсь, это некритично)

2021-03-10 12:28 UTC, vkryvytskyy commented
> Я забыла создать ветку develop. Надеюсь, это некритично)

Не критично, но в следующий раз лучше создавать)

2021-03-10 12:34 UTC, vkryvytskyy requested changes

2021-03-10 12:34 UTC, vkryvytskyy commented on src/inverseRobot.js
> +  }
Используй свойство hasOwnProperty, чтобы проверить есть ли в объекте `result` искомое свойство

2021-03-10 12:34 UTC, vkryvytskyy commented on src/inverseRobot.js
> +  }
Цикл не нужен, можно удалить

2021-03-10 21:06 UTC, vasylevskaya commented on src/inverseRobot.js
> +  }
@vkryvytskyy я добавила, но почему-то не работает. в чем ошибка?)

function inverseRobot(robot) {
  const result = {};

  Object.keys(robot).forEach(function(oldKey) {
    const newKey = robot[oldKey];

    result[newKey] = oldKey;

    **if (result.hasOwnProperty(newKey)) {
      return null;
    }**
  });

  return result;
}

2021-03-12 10:56 UTC, vpolets requested changes
одним циклом і hasOwnProperty можна пройти це завдання

2021-03-12 11:57 UTC, closed without merging