complete
mate-academy/js_inverse_robot pull request #903
Opened 2022-03-29 11:46 UTC by VladSkoromnyi

2022-03-30 14:00 UTC, vlasiuk-anatolii approved these changes
Great job!

2022-03-30 16:30 UTC, Anna-Tkachenko requested changes
Good job!
Try to do this task simpler using only one iteration instead of 3: Object.values (1 iteration), Object.keys (2 iteration) and for (3 iteration)

2022-03-31 10:07 UTC, Anna-Tkachenko approved these changes
В этой задаче уменьшение времени, которое потратилось на выполнение твоей задачи может быть не так заметно, но в больших проектах важно за этим следить и не создавать лишних итераций там, где этого можно избежать

2022-03-31 10:07 UTC, Anna-Tkachenko commented on src/inverseRobot.js
> +  for (const property in robot) {
```suggestion
  for (const key in robot) {
```

2022-03-31 10:07 UTC, Anna-Tkachenko commented on src/inverseRobot.js
> +  for (const property in robot) {
It's key, not property

2024-08-13 09:15 UTC, closed without merging